remote_theme: just-the-docs/just-the-docs

title: Asked and Answered Slackbot
description: A slackbot to help answer common questions
baseurl: "/aaa-bolt-bot/"
url: "https://brown145.github.io"
logo: "/assets/logo.png"
color_scheme: dark

aux_links:
  "Asked and Answered on GitHub":
    - "//github.com/brown145/aaa-bolt-bot"